[meta]
name = "PiPInstaller-MCDR"
author = [{ "github" = "Mooling0602" }]
maintainers = []
description = "Install Python dependencies in MCDR console."
main-branch = "main"
license = "GPL-3.0"

[platform]
remote-hoster = [{ "github" = "https://github.com" }]